Repository ManageIQ/manageiq-graphql, pull requests merged in 2018-03, with the labels that each got.

#46 Remove ActionResultPayload
  lib/manageiq/graphql/types/action_result_payload.rb
Labels: technical debt

#48 Add `execute_graphql` integration macro
  spec/integration/mutations/perform_vm_power_operation_spec.rb
  spec/integration/relay_spec.rb
  spec/integration/tagging_spec.rb
  spec/integration/vms_spec.rb
  spec/support/integration_macros.rb
Labels: developer, test

#44 Add a graphql-explorer plugin
  .gitignore
  app/javascript/graphql-explorer/components/GraphQLExplorer.js
  app/javascript/graphql-explorer/helpers/graphQLFetcher.js
  app/javascript/graphql-explorer/index.js
  app/javascript/packs/graphql-explorer.js
  lib/manageiq/graphql/engine.rb
  package.json
Labels: developer, enhancement

#50 Add providers
  lib/manageiq/graphql/types/provider.rb
  lib/manageiq/graphql/types/query.rb
  spec/integration/providers_spec.rb
Labels: enhancement
